name:                aws-lambda
version:             0.1.0.0
github:              "aztecrex/haskell-lib-aws-lambda"
license:             BSD3
author:              "Greg Wiley"
maintainer:          "aztec.rex@jammm.com"
copyright:           "2018 Greg Wiley"

extra-source-files:
- README.md
- ChangeLog.md

synopsis: Develop computations for AWS Lambda
category: Cloud

description: README on Github at <https://github.com/aztecrex/haskell-lib-aws-lambda#readme>

dependencies:
- base >= 4.7 && < 5
- text

library:
  source-dirs: src

tests:
  aws-lambda-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aws-lambda
    - tasty
    - tasty-hunit
    - tasty-smallcheck

default-extensions:
  - ConstraintKinds
  - DefaultSignatures
  - DeriveFunctor
  - DeriveGeneric
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - MonoLocalBinds
  - GeneralizedNewtypeDeriving
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedStrings
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeOperators

